export enum EBemClassNames {
    button = 'button',
    loader = 'loader',
    container = 'container',
    header = 'header',
    scene = 'scene',
    checkbox = 'checkbox',
    radio = 'radio',
    app = 'app',
    homeScene = 'home-scene',
    formScene = 'form-scene',
    formSceneSidebarMenu = 'form-scene-sidebar-menu',
    formFirstExample = 'form-first-example',
    formSecondExample = 'form-second-example',
    formThirdExample = 'form-third-example',
    homePresentation = 'home-presentation',
    loaderWithInfo = 'loader-with-info',
    textfield = 'textfield',
    scrollbar = 'scrollbar'
}